version: '3.8'

services:
  # Base de datos SQL Server
  autofleet-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autofleet_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sWyeUEUL45!348&3c
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
  